name: Run Tests

on:
  push:
    branches-ignore:
      - main

jobs:

  setup:
    name: Setup project
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  analyze:
    name: Analyze
    needs: setup
    uses: ./.github/workflows/analyze.yml
    secrets: inherit

  tests:
    name: Tests
    needs: setup
    uses: ./.github/workflows/tests.yml
    secrets: inherit
